In [1]:
my_list=[1,2,3,4]

In [4]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr2=np.array(my_mat)

In [9]:
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#3x3 array you known it by number of []

## arrange

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((4,3)) #pa

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.29675978, 0.86893057, 0.74048117, 0.54012312, 0.22250892])

In [21]:
np.random.rand(5,5)

array([[0.03760328, 0.29870206, 0.63838112, 0.9994061 , 0.33283768],
       [0.46357845, 0.6825487 , 0.83277547, 0.95289828, 0.68371999],
       [0.60308119, 0.61947898, 0.82242658, 0.61708382, 0.96204704],
       [0.11114947, 0.81311861, 0.62183397, 0.56725248, 0.3678148 ],
       [0.24976845, 0.13142991, 0.69366852, 0.54336444, 0.79739307]])

In [23]:
np.random.randn(1,3)#random distribution around zero (Gaussian)

array([[-0.42367843,  1.18933736,  1.40391194]])

In [26]:
np.random.randint(1,101,10) #not including the high 

array([86, 96,  2, 35,  2, 26, 82, 83, 42, 96])

In [27]:
##Reshape

In [28]:
arr=np.arange(25)

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
randarr=np.random.randint(0,50,10)

In [31]:
randarr


array([11, 22,  4, 10, 11, 46, 30, 20, 38, 39])

In [32]:
randarr.max()


4

In [33]:
randarr.min()

4

In [34]:
randarr.max()

46

In [35]:
randarr.argmax()#return an index

5

In [38]:
randarr.dtype

dtype('int32')

In [39]:
randarr.shape

(10,)

In [40]:
#y=0

In [42]:
from numpy.random import randint

In [43]:
randint(6)

4

In [46]:
ra=randint(100)


In [47]:
ra

52

##  Indexing

In [49]:
import numpy as np

In [50]:
arr=np.arange(0,10)

In [51]:
arr[5]

5

In [52]:
arr[1:5]

array([1, 2, 3, 4])

In [53]:
arr[:7]#everything up to index 7, 7 included

array([0, 1, 2, 3, 4, 5, 6])

In [55]:
arr[3:] #from index 3 to the end, 3 included

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[0:5]=100

In [66]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [69]:
arr=np.arange(0,11)

In [70]:
slice_arr=arr[4:5]

In [71]:
slice_arr[:]=99


In [72]:
arr

array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9, 10])

In [76]:
arr_copy=arr.copy()

In [77]:
arr_copy

array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9, 10])

In [78]:
arr_copy[:]=00

In [81]:
arr # not boradcasted

array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9, 10])

In [80]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## indexing 2D


In [82]:
import numpy as np


In [86]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [87]:
arr[0][0]

1

In [89]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr[1,2]

6

In [92]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [94]:
 arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [95]:
arr=np.arange(0,11)

In [99]:
bool_arr=arr >5  #it make a check for every element (boolean array)

In [100]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [102]:
arr[bool_arr] # you will only get the result if true

array([ 6,  7,  8,  9, 10])

## Condition selection

In [103]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [104]:
 arr[arr<3]

array([0, 1, 2])

## NumPy Operation

In [105]:
import numpy as np

In [106]:
# element wise

In [107]:
arr =np.arange(0,11)

In [108]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [109]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [110]:
arr/arr

<ipython-input-110-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
1/arr

<ipython-input-111-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [112]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [113]:
#Universal array functions

In [114]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [115]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [116]:
np.max(arr)

10

In [118]:
arr.max()

10

In [119]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [120]:
np.log(arr)

<ipython-input-120-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])